env=prod
BaseUrl=https://bijakproduction.com
Url=https://app.bijakbiz.com
graphQlUrl=https://stgappsync.bijak.biz
apiKey =da2-352pykiclbb4xlvrmzxeth2ryy
logisticAllowedLocation=Agra,Jaipur,Nashik,Kota