env=staging
BaseUrl=https://bijakstaging.com
Url=https://stg.bijak.biz
graphQlUrl=https://stgappsync.bijak.biz
apiKey =da2-352pykiclbb4xlvrmzxeth2ryy
BaseUrlDashboard=https://stg.bijak.biz/logistic";
DsFeedOrderdeatilUrl="https://ne69x2fox6.execute-api.ap-south-1.amazonaws.com/staging";
BaseUrlDsFeed ="https://f9ol52l7gl.execute-api.ap-south-1.amazonaws.com/dev/dsfeed";
graphQlUrlDashBoard="https://vrlvhh4zrbhhtjf3lkags2rbb4.appsync-api.ap-south-1.amazonaws.com";
logisticAllowedLocation=Agra,Jaipur,Nashik,Kota