package util;

public class TestDescriptionConstant {

	public final static String verfiyHomePageUI = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "Verify home page components(homeTab,MyContentTab,StoreTab,NavigationDrawer,ChangeExamContainer,FeedTab,StudyMaterialTab,NotificationIcon,ChangeLanguageBtn,ApplicationLogo)"
			+ "All components should be visible."
			+ "Validate homepage FeedTabs(Ask Doubts,CurrentAffairs,DailyQuiz,Videos,JobAlerts,NotesAndArticles)."
			+ "All FeedTabs should be tappable." + "Validate TestStateBtn(RegisterFree,Attempt,Result)"
			+ "TestState button should be tappable." + "Post title should be clickable."
			+ "User should be able to Play and close the Video post."
			+ "User should able to post comment,like,share and bookmark the post."
			+ "Post should be visible inside bookmark tab."
			+ "User should be able to remove post from BookMark section." + "User should be able to scroll home screen."
			+ "Post title should be clickable." + "User should be able to Play and close the Video post."
			+ "User should able to post comment,like,share and bookmark the post."
			+ "Post should be visible inside bookmark tab."
			+ "User should be able to remove post from BookMark section."
			+ "validate change language btn,notification icon,Change Exam container."
			+ "User should be able to change the language." + "User should be able to open notification page."
			+ "User should be able to change exam type.";

	public final static String verfiySideNavigationDrawerComponent = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to open SideDrawer." + "User should be able to verify sideDrawer."
			+ "Validate BuyStudyMaterial tab,MyContent tab,HelpAndSupportTab,SettingTab,RateUsTab and ReferNowBtn should be tappable.";

	public final static String verfiyCurrentAffairSection = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to open side drawer." + "User should be able to verify sideDrawer."
			+ "User should be able to open CurrentAffair section."
			+ "User should be able to verify CurrentAffair Page component."
			+ "User should be able to open study material." + "User should be able to close studymaterial screen."
			+ "Read indicator should visible on that material."
			+ "User should be able to open filter page by click on filter button."
			+ "User should be able to verify filter page." + "User should be able to select Unread tab."
			+ "User should be able to click apply button." + "Filter page should be closed."
			+ "Read indicator should not be visible on that material." + "User should able to open material."
			+ "Verify current affair material page."
			+ "Verify user should be able to click on audio icon,BookMark icon."
			+ "user should be able to enable audio icon." + "User should be able to enable/Disable BookMark icon."
			+ "BookMark toast message should be visible after enable/disable of bookmark icon."
			+ "User should be able to click on dot icon and FontSize and ReportContent tab should be visible."
			+ "User should be able to select different font size."
			+ "User should be able to like the material and like count should be changed."
			+ "User should be able add or delete comment." + "Material Share button should be tappable.";

	public final static String verfiyJobAlertSection = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to open side drawer." + "User should be able to verify sideDrawer."
			+ "User should be able to open JobAlert section." + "User should be able to verify JobAlert Page component."
			+ "User should be able to open study material." + "User should be able to close studymaterial screen."
			+ "Read indicator should visible on that material."
			+ "User should be able to open filter page by click on filter button."
			+ "User should be able to verify filter page." + "User should be able to select Unread tab."
			+ "User should be able to click apply button." + "Filter page should be closed."
			+ "Read indicator should not be visible on that material." + "User should able to open material."
			+ "Verify JobAlert material page." + "Verify user should be able to click on BookMark icon."
			+ "User should be able to enable/Disable BookMark icon."
			+ "BookMark toast message should be visible after enable/disable of bookmark icon."
			+ "User should be able to click on dot icon and FontSize and ReportContent tab should be visible."
			+ "User should be able to select different font size."
			+ "User should be able to like the material and like count should be changed."
			+ "User should be able add or delete comment." + "Material Share button should be tappable.";

	public final static String verifyNotesAndArticlesSection = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to open side drawer." + "User should be able to verify sideDrawer."
			+ "User should be able to open NotesAndArticles section."
			+ "User should be able to verify NotesAndArticles Page component."
			+ "User should be able to open study material." + "User should be able to close studymaterial screen."
			+ "Read indicator should visible on that material."
			+ "User should be able to open filter page by click on filter button."
			+ "User should be able to verify filter page." + "User should be able to select Unread tab."
			+ "User should be able to click apply button." + "Filter page should be closed."
			+ "Read indicator should not be visible on that material." + "User should able to open material."
			+ "Verify NotesAndArticles material page." + "Verify user should be able to click on BookMark icon."
			+ "User should be able to enable/Disable BookMark icon."
			+ "BookMark toast message should be visible after enable/disable of bookmark icon."
			+ "User should be able to click on dot icon and FontSize and ReportContent tab should be visible."
			+ "User should be able to select different font size."
			+ "User should be able to like the material and like count should be changed."
			+ "User should be able add or delete comment." + "Material Share button should be tappable.";

	public final static String verifyPowerCapsulesSection = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to open side drawer." + "User should be able to verify sideDrawer."
			+ "User should be able to open Powercapsules section."
			+ "User should be able to verify Powercapsules Page component."
			+ "User should be able to open study material." + "User should be able to close studymaterial screen."
			+ "Read indicator should visible on that material."
			+ "User should be able to open filter page by click on filter button."
			+ "User should be able to verify filter page." + "User should be able to select Unread tab."
			+ "User should be able to click apply button." + "Filter Page should be closed."
			+ "Read indicator should not be visible on that material." + "User should able to open material."
			+ "Verify Powercapsules material page." + "PowerCapsule share button should be tappable."
			+ "PowerCapsule pdf button should be tappable." + "User should be able to select different font size."
			+ "User should be able to select pdf chapter button.";

	public final static String verifyVideoSection = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to open side drawer." + "User should be able to verify sideDrawer."
			+ "User should be able to open Video section."
			+ "User should be able to verify VideoSection Page component." + "User should be able to open Recent tab."
			+ "User should be able to open filter page by click on filter button."
			+ "User should be able to verify filter page." + "User should be able to select commingSoon tab."
			+ "User should be able to click on apply button." + "UpComming tag should be visible on videoMaterial."
			+ "User should be able to enter topic in search textfield."
			+ "ViewAll button should be displayed and it should be tappable." + "Searched video should be visible."
			+ "User should be able to click on Dot icon and BookMark and ShareVideo tab should be visible."
			+ "User should be able to click AddToBookMark/DeleteToBookMark and user should able to see appropriate toast message."
			+ "User should be able to click shareVideo tab.";

	public final static String verifyQuizeSection = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to open side drawer." + "User should be able to verify sideDrawer."
			+ "User should be able to open DailyQuizzes section."
			+ "User should be able to verify DailyQuizzes Page component."
			+ "User should be able to open different quizze tab." + "Verify user is able to verify DailyQuizzFeed page."
			+ "Verify user should be able to download the quize.";

	public final static String verifyStudyMaterialTab = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click StudyMaterial tab."
			+ "User should be able to open all the StudyMaterial tabs and validate the page title.";

	public final static String verifyCompletePaymentByUsingUPI = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click store btn" + "User should be able to verify store page."
			+ "User should be able to click on EBook icon."
			+ "User should be able to click EBook randomly from EBook list."
			+ "User should be able to verify UnPurchasePage component." + "User should be able to click on BUY button."
			+ "User should be able to fill userDetails form." + "User should able to click on continue button."
			+ "User should be able to see payment option screen." + "User should be able to click UPI payment option."
			+ "Validate UPI payment screen." + "User should be able to verify UPI ID form."
			+ "User should be able to click on payment language change button."
			+ "User should be able to verify language screen." + "User should be able to close Language screen."
			+ "User should be able to open Account tab."
			+ "EditContactDetails and ChangeLanguage tab should be visible."
			+ "User should be able to open EditContactDetails page."
			+ "User should be able to enter Mobile number and EmailId."
			+ "User should be able to click on continue btn." + "User should be able to open/Close Change language tab."
			+ "User should be able to enter UPI Id." + "User should be able to open/close ViewDetails tab."
			+ "User should be able to click on PayNow button." + "User should be able to see the RateUs PopUp."
			+ "User should be able to close RateUs PopUp window." + "User should be able to verify OrderSuccess page.";

	public final static String verifyPayTMTypePayment = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click store btn" + "User should be able to verify store page."
			+ "User should be able to click on EBook icon."
			+ "User should be able to click EBook randomly from EBook list."
			+ "User should be able to verify UnPurchasePage component." + "User should be able to click on BUY button."
			+ "User should be able to fill userDetails form." + "User should able to click on continue button."
			+ "User should be able to see payment option screen."
			+ "User should be able to click PayTM type payment option." + "User should be able to verify PayTM form."
			+ "User should be able to enter mobile number." + "User should be able to open checkOutCardTab."
			+ "User should be able to verify CheckOutCard Page." + "User should be able to close CheckOutCard page."
			+ "User should be able to open checkOutUPITab." + "User should be able to verify CheckOutUPI Page."
			+ "User should be able to close CheckOutUPI page." + "User should be able to open checkOutNetBankingTab."
			+ "User should be able to verify CheckOutNetBanking Page."
			+ "User should be able to close CheckOutNetBanking page." + "User able to click on PayTM back button."
			+ "User able to verify and click on SkipFeedBack button.";

	public final static String verifyDebitCardTypePayment = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click store btn" + "User should be able to verify store page."
			+ "User should be able to click on EBook icon."
			+ "User should be able to click EBook randomly from EBook list."
			+ "User should be able to verify UnPurchasePage component." + "User should be able to click on BUY button."
			+ "User should be able to fill userDetails form." + "User should able to click on continue button."
			+ "User should be able to see payment option screen."
			+ "User should be able to click DebitCard payment option." + "Validate DebitCard payment screen."
			+ "User should be able to verify AddCard form."
			+ "User should be able to add card number,CardExpireDate,CardHolderName,CardCVV."
			+ "User should be able to open/close ViewDetails tab." + "User should be able to close AddCard form.";

	public final static String verifyCreditCardTypePayment = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click store btn" + "User should be able to verify store page."
			+ "User should be able to click on EBook icon."
			+ "User should be able to click EBook randomly from EBook list."
			+ "User should be able to verify UnPurchasePage component." + "User should be able to click on BUY button."
			+ "User should be able to fill userDetails form." + "User should able to click on continue button."
			+ "User should be able to see payment option screen."
			+ "User should be able to click CreditCard payment option." + "Validate CreditCard payment screen."
			+ "User should be able to verify AddCard form."
			+ "User should be able to add card number,CardExpireDate,CardHolderName,CardCVV."
			+ "User should be able to open/close ViewDetails tab." + "User should be able to close AddCard form.";

	public final static String verifyEMITypePayment = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click store btn" + "User should be able to verify store page."
			+ "User should be able to click on EBook icon."
			+ "User should be able to click EBook randomly from EBook list."
			+ "User should be able to verify UnPurchasePage component." + "User should be able to click on BUY button."
			+ "User should be able to fill userDetails form." + "User should able to click on continue button."
			+ "User should be able to see payment option screen."
			+ "User should be able to click EMI type payment option." + "User should be able to verify Bank EMI form."
			+ "User should be able to click on payment language change button."
			+ "User should be able to verify language screen." + "User should be able to close Language screen."
			+ "User should be able to open/close ViewDetails tab." + "User should be able to close Bank EMI Form.";

	public final static String verifyCompletePaymentByUsingNetBanking = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click store btn" + "User should be able to verify store page."
			+ "User should be able to click on EBook icon."
			+ "User should be able to click EBook randomly from EBook list."
			+ "User should be able to verify UnPurchasePage component." + "User should be able to click on BUY button."
			+ "User should be able to fill userDetails form." + "User should able to click on continue button."
			+ "User should be able to see payment option screen."
			+ "User should be able to click NetBanking payment option." + "Validate NetBanking payment screen."
			+ "User should be able to verify NetBanking form." + "User should be able to open DifferentBank dropdown."
			+ "User should be able to verify DifferentBank DropDown page."
			+ "User should be able to close DifferentBank dropdown page."
			+ "User should be able to click on payment language change button."
			+ "User should be able to verify language screen." + "User should be able to close Language screen."
			+ "User should be able to open Account tab."
			+ "EditContactDetails and ChangeLanguage tab should be visible."
			+ "User should be able to open EditContactDetails page."
			+ "User should be able to enter Mobile number and EmailId."
			+ "User should be able to click on continue btn." + "User should be able to open/Close Change language tab."
			+ "User should be able to open/close ViewDetails tab." + "User should be able to select SBI/Kotak bank tab."
			+ "User should be able to click on PayNow button." + "User should be able to click on Failure button"
			+ "User should be able to see Failed Payment title." + "User should be able to click on Try Again button."
			+ "User Should be able to see and click on PayNow button."
			+ "User should be able to click on Success button." + "User should be able to see the RateUs PopUp."
			+ "User should be able to close RateUs PopUp window." + "User should be able to verify OrderSuccess page.";

	public final static String verifyOtherWalletypePayment = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click store btn" + "User should be able to verify store page."
			+ "User should be able to click on EBook icon."
			+ "User should be able to click EBook randomly from EBook list."
			+ "User should be able to verify UnPurchasePage component." + "User should be able to click on BUY button."
			+ "User should be able to fill userDetails form." + "User should able to click on continue button."
			+ "User should be able to see payment option screen."
			+ "User should be able to click OtherWallet payment option." + "Validate OtherWallet payment screen."
			+ "User should be able to verify SelectWallet form."
			+ "User should be able to click on payment language change button."
			+ "User should be able to verify language screen." + "User should be able to close Language screen."
			+ "User should be able to open Account tab."
			+ "EditContactDetails and ChangeLanguage tab should be visible."
			+ "User should be able to open EditContactDetails page."
			+ "User should be able to enter Mobile number and EmailId."
			+ "User should be able to click on continue btn." + "User should be able to open/Close Change language tab."
			+ "User should be able to open/close ViewDetails tab." + "User should be able to close Wallet form.";

	public final static String verifyMockTestStoreFront = "User should be able to Create Mock through API."
			+ "User should be able to assign test series to package through API."
			+ "User should be able to select Exam type and Language."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click on MyContent button." + "User should be able to verify MyContent page."
			+ "User should be able to click on Purchase button." + "Purchased package should be visible."
			+ "User should be able to click on Purchased package."
			+ "User should be able to handle SearchInstruction popUp."
			+ "User should be able to click on purchased course." + "User should be able to verify testseries page."
			+ "User should be able to verify CreatedMock." + "User should be able to download CreatedMock."
			+ "User should be able to see ATTEMPT button on CreatedMock."
			+ "User should be able to click on ATTEMPT button." + "User should be able to verify Instruction page."
			+ "User should be able to click on StartTest button." + "User should be able to click on Filter button."
			+ "User should be able to select question answer option."
			+ "User should be able to click on SaveAndNext button."
			+ "User should be able to complete the test by click on submit button."
			+ "User should be able to handle TestRating popup." + "User should be able to verify and close Coin PopUp."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to verify TestAnalysisDailyQuizPage."
			+ "User should be able to close TestAnalysisDailyQuizPage."
			+ "User should be able to see Result button on CreatedMock."
			+ "User should be able to click on Result button."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to see Correct,Wrong and skip answer count."
			+ "User able to click on Solution button." + "User should be able to verify Solution page."
			+ "In Solution page ShowCorrectAnswer button count should be equal to Sum of WrongAnswer and Not Answered count.";

	public final static String verifyAttemptAndReAttemptMockTestWithOutInternet = "User should be able to Create Mock through API."
			+ "User should be able to assign test series to package through API."
			+ "User should be able to select Exam type and Language."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click on MyContent button." + "User should be able to verify MyContent page."
			+ "User should be able to click on Purchase button." + "Purchased package should be visible."
			+ "User should be able to click on Purchased package."
			+ "User should be able to handle SearchInstruction popUp."
			+ "User should be able to click on purchased course." + "User should be able to verify testseries page."
			+ "User should be able to verify CreatedMock." + "User should be able to download CreatedMock."
			+ "User should be able to TurnOff mobile internet."
			+ "User should be able to see ATTEMPT button on CreatedMock."
			+ "User should be able to click on ATTEMPT button." + "User should be able to verify Instruction page."
			+ "User should be able to click on StartTest button." + "User should be able to click on Filter button."
			+ "User should be able to select question answer option."
			+ "User should be able to click on SaveAndNext button."
			+ "User should be able to complete the test by click on submit button."
			+ "User should be able to handle TestRating popup." + "User should get InterNet OFF Toast."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to verify TestAnalysisDailyQuizPage."
			+ "User should be able to close TestAnalysisDailyQuizPage."
			+ "User should be able to see Result button on CreatedMock."
			+ "User should be able to click on Result button." + "User should get InterNet OFF Toast."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to click on ReAttempt button." + "User should be able to verify Instruction page."
			+ "User should be able to click on StartTest button." + "User should be able to click on Filter button."
			+ "User should be able to select question answer option."
			+ "User should be able to click on SaveAndNext button."
			+ "User should be able to complete the test by click on submit button."
			+ "User should be able to handle TestRating popup." + "User should get InterNet OFF Toast."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to verify TestAnalysisDailyQuizPage.";

	public final static String verifyResumeMockTest = "User should be able to Create Mock through API."
			+ "User should be able to assign test series to package through API."
			+ "User should be able to select Exam type and Language."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click on MyContent button." + "User should be able to verify MyContent page."
			+ "User should be able to click on Purchase button." + "Purchased package should be visible."
			+ "User should be able to click on Purchased package."
			+ "User should be able to handle SearchInstruction popUp."
			+ "User should be able to click on purchased course." + "User should be able to verify testseries page."
			+ "User should be able to verify CreatedMock." + "User should be able to download CreatedMock."
			+ "User should be able to see ATTEMPT button on CreatedMock."
			+ "User should be able to click on ATTEMPT button." + "User should be able to verify Instruction page."
			+ "User should be able to click on StartTest button." + "User should be able to click on Filter button."
			+ "User should be able to select question answer option."
			+ "User should be able to click on SaveAndNext button."
			+ "User should be able to click on test Pause button."
			+ "User should be able to see the RESUME button on CreatedMock."
			+ "User should be able to click on RESUME button."
			+ "User should be able to see the Test pane and It should be same with Paused page."
			+ "User should be able to complete the test by click on submit button."
			+ "User should be able to handle TestRating popup." + "User should be able to verify and close Coin PopUp."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to verify TestAnalysisDailyQuizPage."
			+ "User should be able to close TestAnalysisDailyQuizPage."
			+ "User should be able to see Result button on CreatedMock."
			+ "User should be able to click on Result button."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to click on ShareScoreCard button."
			+ "User should be able to verify ScoreCard popUp page."
			+ "User should be able to click on ShareWithFriend button."
			+ "User should be able to Verify and close ShareWithFriend page."
			+ "User should be able to close ShareScoreCard page.";

	public final static String verifyMockTestStoreFrontWithCalculator = "User should be able to Create Mock through API."
			+ "User should be able to assign test series to package through API."
			+ "User should be able to select Exam type and Language."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click on MyContent button." + "User should be able to verify MyContent page."
			+ "User should be able to click on Purchase button." + "Purchased package should be visible."
			+ "User should be able to click on Purchased package."
			+ "User should be able to handle SearchInstruction popUp."
			+ "User should be able to click on purchased course." + "User should be able to verify testseries page."
			+ "User should be able to verify CreatedMock." + "User should be able to download CreatedMock."
			+ "User should be able to see ATTEMPT button on CreatedMock."
			+ "User should be able to click on ATTEMPT button." + "User should be able to verify Instruction page."
			+ "User should be able to click on StartTest button." + "User should be able to click on Filter button."
			+ "User should be able to open by click on Calculator button"
			+ "User should be able to see and close Calculator screen."
			+ "User should be able to select question answer option."
			+ "User should be able to click on SaveAndNext button."
			+ "User should be able to complete the test by click on submit button."
			+ "User should be able to handle TestRating popup." + "User should be able to verify and close Coin PopUp."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to verify TestAnalysisDailyQuizPage."
			+ "User should be able to close TestAnalysisDailyQuizPage."
			+ "User should be able to see Result button on CreatedMock."
			+ "User should be able to click on Result button."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to see Correct,Wrong and skip answer count."
			+ "User able to click on Solution button." + "User should be able to verify Solution page."
			+ "User should be able to open by click on Calculator button"
			+ "User should be able to see and close Calculator screen."
			+ "In Solution page ShowCorrectAnswer button count should be equal to Sum of WrongAnswer and Not Answered count.";

	public final static String verifyCutOffMockTest = "User should be able to Create Mock through API."
			+ "User should be able to assign test series to package through API."
			+ "User should be able to select Exam type and Language."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click on MyContent button." + "User should be able to verify MyContent page."
			+ "User should be able to click on Purchase button." + "Purchased package should be visible."
			+ "User should be able to click on Purchased package."
			+ "User should be able to handle SearchInstruction popUp."
			+ "User should be able to click on purchased course." + "User should be able to verify testseries page."
			+ "User should be able to see CutOff mark tag and it should contains 60."
			+ "User should be able to verify CreatedMock." + "User should be able to download CreatedMock."
			+ "User should be able to see ATTEMPT button on CreatedMock."
			+ "User should be able to click on ATTEMPT button."
			+ "User should be able to see CutOff mark Instruction text and it should contains 60."
			+ "User should be able to verify Instruction page." + "User should be able to click on StartTest button."
			+ "User should be able to click on Filter button." + "User should be able to select question answer option."
			+ "User should be able to click on SaveAndNext button."
			+ "User should be able to complete the test by click on submit button."
			+ "User should be able to handle TestRating popup." + "User should be able to verify and close Coin PopUp."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to see CutOff mark LayOut."
			+ "User should be able to verify TestAnalysisDailyQuizPage."
			+ "User should be able to close TestAnalysisDailyQuizPage."
			+ "User should be able to see Result button on CreatedMock."
			+ "User should be able to click on Result button."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to see Correct,Wrong and skip answer count."
			+ "User able to click on Solution button." + "User should be able to verify Solution page."
			+ "In Solution page ShowCorrectAnswer button count should be equal to Sum of WrongAnswer and Not Answered count.";

	public final static String verifyMultiLanguageMockTest = "User should be able to Create Mock through API."
			+ "User should be able to assign test series to package through API."
			+ "User should be able to select Exam type and Language."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click on MyContent button." + "User should be able to verify MyContent page."
			+ "User should be able to click on Purchase button." + "Purchased package should be visible."
			+ "User should be able to click on Purchased package."
			+ "User should be able to handle SearchInstruction popUp."
			+ "User should be able to click on purchased course." + "User should be able to verify testseries page."
			+ "User should be able to see CutOff mark tag and it should contains 60."
			+ "User should be able to verify CreatedMock." + "User should be able to download CreatedMock."
			+ "User should be able to see ATTEMPT button on CreatedMock."
			+ "User should be able to click on ATTEMPT button."
			+ "User should be able to see CutOff mark Instruction text and it should contains 60."
			+ "User should be able to verify Instruction page." + "User should be able to select multiple language."
			+ "User should be able to click on StartTest button."
			+ "User should be able to see language button on each question screen and Language button should be tappable."
			+ "User should be able to click on Filter button." + "User should be able to select question answer option."
			+ "User should be able to open and close calculator on each screen."
			+ "User should be able to click on SaveAndNext button."
			+ "User should be able to complete the test by click on submit button."
			+ "User should be able to handle TestRating popup." + "User should be able to verify and close Coin PopUp."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to see CutOff mark LayOut."
			+ "User should be able to verify TestAnalysisDailyQuizPage."
			+ "User should be able to close TestAnalysisDailyQuizPage."
			+ "User should be able to see Result button on CreatedMock."
			+ "User should be able to click on Result button."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to REATTEMPT the mock."
			+ "User should be able to see Correct,Wrong and skip answer count."
			+ "User able to click on Solution button." + "User should be able to verify Solution page."
			+ "In Solution page ShowCorrectAnswer button count should be equal to Sum of WrongAnswer and Not Answered count."
			+ "User should be able to see language button on each solution screen and Language button should be tappable."
			+ "User should be able to open and close calculator on each screen.";

	public final static String verifyMultiQuestionMockTest = "User should be able to Create Mock through API."
			+ "User should be able to assign test series to package through API."
			+ "User should be able to select Exam type and Language."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click on MyContent button." + "User should be able to verify MyContent page."
			+ "User should be able to click on Purchase button." + "Purchased package should be visible."
			+ "User should be able to click on Purchased package."
			+ "User should be able to handle SearchInstruction popUp."
			+ "User should be able to click on purchased course." + "User should be able to verify testseries page."
			+ "User should be able to see CutOff mark tag and it should contains 60."
			+ "User should be able to verify CreatedMock." + "User should be able to download CreatedMock."
			+ "User should be able to see ATTEMPT button on CreatedMock."
			+ "User should be able to click on ATTEMPT button."
			+ "User should be able to see CutOff mark Instruction text and it should contains 60."
			+ "User should be able to verify Instruction page." + "User should be able to click on StartTest button."
			+ "User should be able to click on Filter button." + "User should be able to select question answer option."
			+ "User should be able to see and answer Multiple type question."
			+ "User should be able to open and close calculator on each screen."
			+ "User should be able to click on SaveAndNext button."
			+ "User should be able to complete the test by click on submit button."
			+ "User should be able to handle TestRating popup." + "User should be able to verify and close Coin PopUp."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to see CutOff mark LayOut."
			+ "User should be able to verify TestAnalysisDailyQuizPage."
			+ "User should be able to close TestAnalysisDailyQuizPage."
			+ "User should be able to see Result button on CreatedMock."
			+ "User should be able to click on Result button."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to verify TestAnalysisDailyQuizPage."
			+ "User should be able to close TestAnalysisDailyQuizPage.";

	public final static String verifySectionalTimeLimitMockTest = "User should be able to Create Mock through API."
			+ "User should be able to assign test series to package through API."
			+ "User should be able to select Exam type and Language."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click on MyContent button." + "User should be able to verify MyContent page."
			+ "User should be able to click on Purchase button." + "Purchased package should be visible."
			+ "User should be able to click on Purchased package."
			+ "User should be able to handle SearchInstruction popUp."
			+ "User should be able to click on purchased course." + "User should be able to verify testseries page."
			+ "User should be able to verify CreatedMock." + "User should be able to download CreatedMock."
			+ "User should be able to see ATTEMPT button on CreatedMock."
			+ "User should be able to click on ATTEMPT button." + "User should be able to verify Instruction page."
			+ "User should be able to click on StartTest button." + "User should be able to see the section DropDown."
			+ "User should be able to change  section through section DropDown."
			+ "While changing section user should be able to see the Section skip PopUp page."
			+ "User should be able to skip the section by click on skip button"
			+ "In last section user should be able to see the rating popup after time got finished."
			+ "User should be able to handle the rating popup." + "User should be able to click ReAttempt button."
			+ "User should be able to click on StartTest button."
			+ "User should be able to see Section time end popup page, once section time got overed."
			+ "user should be able to click Pause Section button."
			+ "User should be able to see the Resume button on created Mock."
			+ "user should be able to click on Resume button." + "User should be able to click on ResumeTest button."
			+ "User should be able to see Section time end popup page."
			+ "user should be able to click NextSection button." + "User should be able to see next section."
			+ "user should be able to Submit the Test." + "User should be able to handle rating popup."
			+ "User should be able to click ReAttempt button." + "User should be able to click on StartTest button."
			+ "User should be able to take and Submit the test."
			+ "End of each section user should see Skip Section PopUp page and able to handle it."
			+ "End of last section user should not get SkipSection PopUp page."
			+ "User should be able to handle Rating PopUp." + "User should be able to handle Coin PopUp."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to verify TestAnalysisDailyQuizPage."
			+ "User should be able to close TestAnalysisDailyQuizPage."
			+ "User should be able to see Result button on CreatedMock."
			+ "User should be able to click on Result button."
			+ "User should be able to compare actual screen with present screen and the result should be more than 90%."
			+ "User should be able to see Correct,Wrong and skip answer count."
			+ "User able to click on Solution button." + "User should be able to verify Solution page."
			+ "In Solution page ShowCorrectAnswer button count should be equal to Sum of WrongAnswer and Not Answered count."
			+ "User should be able to see the section Title on each screen.";

	public final static String verifyDoubtRoomUI = "User should be able to create DoubtRoom slot through API."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click on Store button." + "User should be able to verify Store page."
			+ "User should be able to click on Search icon."
			+ "User should be able to enter Package name in Search icon."
			+ "User should be able to select Product type." + "User should be able to select searched Package name."
			+ "User should be able to apply Coupon code." + "User should be able to click on BUY now button."
			+ "User should be able to see UserDetailsForm if ProductType is Books or AllType."
			+ "User should be able to fill the User details form." + "User should be able to click on Continue button."
			+ "User should be able to skip FeedBack form." + "User should be able to get StartLearningTitle."
			+ "User should navigate to Store page by click on android back button 3 times."
			+ "User should be able to click on MyContent button." + "User should be able to click on Purchase button."
			+ "User should be able to see Purchased Package in PurchasePackage section."
			+ "User should be able to click on Purchased Package." + "User should be able to select AllCourseCheckBox."
			+ "User should be able to click on ApplyFilter button." + "User should be able to click on Done button."
			+ "User should be able to validate Purchase Package UI."
			+ "User should be able to click on ExamModeSwitch button." + "User should be able to see DoubtRoom button."
			+ "User should be able to see and click on ManageExam button."
			+ "User should be able to see AllCourseCheckBox." + "User should be able to select AllCourseCheckBox."
			+ "User should be able to click on ApplyFilter button."
			+ "User should be able to click Different course tab."
			+ "User should be able to see DoubtRoom button on each course tab page."
			+ "User should be able to open and close DoubtRoom screen by click on DoubtRoom button on each CourseTab screen."
			+ "User should be able to click on DoubtRoom button." + "User should be able to validate DoubtRoom Page."
			+ "User should be able to click on JoinNow button." + "User should be able to handle Page Loading."
			+ "User should be able to validate Welcome PopUp page." + "User should be able to click on Join button."
			+ "User should be able to see and click on OnlyThisTime button."
			+ "User should be able to validate LiveDoubtRoom page UI."
			+ "User should be able to change the screen mode." + "User should be able to enable DataSaver button."
			+ "User should be able to click on Dot icon." + "User should be able to see Report Issue tab."
			+ "User should be able to select all report option list." + "User should be able to Report a DoubtClass."
			+ "User should be able to enter message in message text field." + "User should be able to raise the hand."
			+ "User should be able to exit and ReJoin the class.";

	public final static String verifyVideoCourse = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click on Store button." + "User should be able to verify Store page."
			+ "User should be able to click on Search icon."
			+ "User should be able to enter Package name in Search icon."
			+ "User should be able to select Product type." + "User should be able to select searched Package name."
			+ "User should be able to apply Coupon code." + "User should be able to click on BUY now button."
			+ "User should be able to see UserDetailsForm if ProductType is Books or AllType."
			+ "User should be able to fill the User details form." + "User should be able to click on Continue button."
			+ "User should be able to skip FeedBack form." + "User should be able to get StartLearningTitle."
			+ "User should navigate to Store page by click on android back button 3 times."
			+ "User should be able to click on MyContent button." + "User should be able to click on Purchase button."
			+ "User should be able to see Purchased Package in PurchasePackage section."
			+ "User should be able to click on Purchased Package." + "User should be able to click on Purchased video."
			+ "User should be able to click on GotIt button."
			+ "User should be able to validate PurchasedVideoCourse UI."
			+ "User should be able to click on VideoCourse Share button." + "User should be able to close Share screen."
			+ "User should be able to click on PlayerViewState button."
			+ "User should be able to select different video PlayBack speed by click on PlayBackSpeed button."
			+ "User should be able to change video fullscreen by click on VideoFullScreen button.";

	public final static String verifyVideoCourseDownload = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click on Store button." + "User should be able to verify Store page."
			+ "User should be able to click on Search icon."
			+ "User should be able to enter Package name in Search icon."
			+ "User should be able to select Product type." + "User should be able to select searched Package name."
			+ "User should be able to apply Coupon code." + "User should be able to click on BUY now button."
			+ "User should be able to see UserDetailsForm if ProductType is Books or AllType."
			+ "User should be able to fill the User details form." + "User should be able to click on Continue button."
			+ "User should be able to skip FeedBack form." + "User should be able to get StartLearningTitle."
			+ "User should navigate to Store page by click on android back button 3 times."
			+ "User should be able to click on MyContent button." + "User should be able to click on Purchase button."
			+ "User should be able to see Purchased Package in PurchasePackage section."
			+ "User should be able to click on Purchased Package." + "User should be able to click on Purchased video."
			+ "User should be able to click on GotIt button."
			+ "User should be able to open and close Description page by click on Video description button."
			+ "User should be able to click on video download button."
			+ "User should be able to download videos on different quality."
			+ "User should be able to navigate to VideoDownload section."
			+ "User should be able to see Downloaded video on Download section."
			+ "User should be able to Play Downloaded video with internet."
			+ "User should be able to TurnOff the internet."
			+ "User should be able to play Downloaded videos without internet."
			+ "User should be able to Turn ON the internet." + "User should be navigate to Downloaded section."
			+ "User should be able to click on Downloaded video."
			+ "User should be able to Delete all the downloaded video by click on Download button."
			+ "User should navigate to Download section." + "User not able to see the Downloaded video."
			+ "User should be able to see the Empty state title.";

	public final static String verifyLiveClassRecordedSessionUI = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click on Store button." + "User should be able to verify Store page."
			+ "User should be able to click on Search icon."
			+ "User should be able to enter Package name in Search icon."
			+ "User should be able to select Product type." + "User should be able to select searched Package name."
			+ "User should be able to apply Coupon code." + "User should be able to click on BUY now button."
			+ "User should be able to see UserDetailsForm if ProductType is Books or AllType."
			+ "User should be able to fill the User details form." + "User should be able to click on Continue button."
			+ "User should be able to skip FeedBack form." + "User should be able to get StartLearningTitle."
			+ "User should navigate to Store page by click on android back button 3 times."
			+ "User should be able to click on MyContent button." + "User should be able to click on Purchase button."
			+ "User should be able to see Purchased Package in PurchasePackage section."
			+ "User should be able to click on Purchased Package."
			+ "User should be able to click on Purchased LiveClass."
			+ "User should be able to handle Notification popUp" + "User should be able to click on GotIt button."
			+ "User should be able to validate PurchasedLiveClass UI."
			+ "User should be able to click on LiveClass Share button." + "User should be able to close Share screen."
			+ "User should be able to open and close Description page by click on LiveClass Description button."
			+ "User should be able to click on NotifyMe Toggle button.";

	public final static String verifyDownloadOnRecordedLiveClass = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click on Store button." + "User should be able to verify Store page."
			+ "User should be able to click on Search icon."
			+ "User should be able to enter Package name in Search icon."
			+ "User should be able to select Product type." + "User should be able to select searched Package name."
			+ "User should be able to apply Coupon code." + "User should be able to click on BUY now button."
			+ "User should be able to see UserDetailsForm if ProductType is Books or AllType."
			+ "User should be able to fill the User details form." + "User should be able to click on Continue button."
			+ "User should be able to skip FeedBack form." + "User should be able to get StartLearningTitle."
			+ "User should navigate to Store page by click on android back button 3 times."
			+ "User should be able to click on MyContent button." + "User should be able to click on Purchase button."
			+ "User should be able to see Purchased Package in PurchasePackage section."
			+ "User should be able to click on Purchased Package."
			+ "User should be able to click on Purchased LiveClass."
			+ "User should be able to handle Notification popUp." + "User should be able to click on GotIt button."
			+ "User should be able to click On HandOut button" + "User should be able to Download and DElete Handouts."
			+ "User should be able to click on RecorededLiveClass download button."
			+ "User should be able to download RecorededLiveClass on different quality."
			+ "User should be able to navigate to VideoDownload section."
			+ "User should be able to see Downloaded video on Download section."
			+ "User should be able to Play Downloaded video with internet."
			+ "User should be able to TurnOff the internet."
			+ "User should be able to play Downloaded videos without internet."
			+ "User should be able to Turn ON the internet." + "User should be navigate to Downloaded section."
			+ "User should be able to click on Downloaded video."
			+ "User should be able to Delete all the downloaded video by click on Download button."
			+ "User should navigate to Download section." + "User not able to see the Downloaded video."
			+ "User should be able to see the Empty state title.";

	public final static String verifyStudentScreenOnLiveClass = "User should be able to Schedule a class through API."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click on Store button." + "User should be able to verify Store page."
			+ "User should be able to click on Search icon."
			+ "User should be able to enter Package name in Search icon."
			+ "User should be able to select Product type." + "User should be able to select searched Package name."
			+ "User should be able to click on BUY now button."
			+ "User should be able to see UserDetailsForm if ProductType is Books or AllType."
			+ "User should be able to fill the User details form." + "User should be able to click on Continue button."
			+ "User should be able to purchase package by using UPI type payment option."
			+ "User should be able to skip FeedBack form." + "User should be able to get StartLearningTitle."
			+ "User should navigate to Store page by click on android back button 3 times."
			+ "User should be able to click on MyContent button." + "User should be able to click on Purchase button."
			+ "User should be able to see Purchased Package in PurchasePackage section."
			+ "User should be able to click on Purchased Package."
			+ "User should be able to click on Purchased LiveClass."
			+ "User should be able to handle Notification popUp." + "User should be able to click on GotIt button."
			+ "User should be able to click on JoinLive button."
			+ "User should be able to validate ClassNotStartedVideoScreen UI."
			+ "User should be able to change screen size by click on Window ReSize button."
			+ "User should be able to click on videoQuality button ."
			+ "Only Auto Quality option should be visible on Quality screen. "
			+ "User should be able to validate ChatWindow."
			+ "User should be able to enter message in message textField." + "User should be able to send message."
			+ "Sent Message should be visible on chat window."
			+ "User should be able to open Report PopUp page by click on Report button."
			+ "User should be able to select all the Report option." + "User should be able to Report a LiveClass."
			+ "User should be able to Exit the class.";

	public final static String verifyOptionFixMockTest = "User should be able to Create Option Fix Mock through API."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click on StudyMaterial tab." + "User should be able to verify StudyMaterial page."
			+ "User should be able to click on Scholarship tab."
			+ "User should be able to click on Register Link of Created Mock."
			+ "User should be able to click on RegisterForFree button."
			+ "User should be able to verify Successful register PopUp."
			+ "User should be able to navigate StudyMaterial tab page."
			+ "User should be able to click on Scholarship tab."
			+ "User should be able to see ATTEMPT button on CreatedMock."
			+ "User should be able to click on ATTEMPT button." + "User should be able to click on StartTest button."
			+ "User should be able to verify Instruction page." + "User should be able to click on StartTest button."
			+ "User should be able to validate Exam Section dropdown."
			+ "User should be able to change section by click on ExamSection dropdown."
			+ "User should be able to click on Filter button." + "User should be able to select question answer option."
			+ "User should be able to click on SaveAndNext button."
			+ "User should be able to complete the test by click on submit button."
			+ "User should be able to verify Result Awaited screen."
			+ "User should be able to close result Awaited screen by click on back button."
			+ "User should be able to see Timer on CreatedMock." + "User should be able to click On Timer ."
			+ "User should be able to verify Result Awaited screen.";

	public final static String verifyOptionalMockTest = "User should be able to Create Optional Mock through API."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click on StudyMaterial tab." + "User should be able to verify StudyMaterial page."
			+ "User should be able to click on DailyTest tab." + "User should be able to download CreatedMock."
			+ "User should be able to see ATTEMPT button on CreatedMock."
			+ "User should be able to click on ATTEMPT button." + "User should be able to verify Instruction page."
			+ "User should be able to click on StartTest button." + "User should be able to click on Filter button."
			+ "User should be able to select question answer option."
			+ "User should be able to click on SaveAndNext button."
			+ "User should be able to complete the test by click on submit button."
			+ "User should be able to handle TestRating popup." + "User should be able to verify and close Coin PopUp."
			+ "User should be able to verify TestAnalysisDailyQuizPage."
			+ "User should be able to close TestAnalysisDailyQuizPage."
			+ "User should be able to see Result button on CreatedMock."
			+ "User should be able to click on Result button."
			+ "User should be able to verify TestAnalysisDailyQuizPage.";

	public final static String verifyPDPWithOutDiscount = "User should be able to create package LiveClass package through API."
			+ "User should be able to get Package title and Primary Validity time."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click store btn" + "User should be able to verify store page."
			+ "User should be able to search package title through search icon."
			+ "User should be able to see Created package and able to click it."
			+ "User should be able to see Primary Validity time period."
			+ "User should be able to validate ValidityTime period DropDown."
			+ "User should be able to see Corresponding validity time period by changing DropDown list."
			+ "User should be able to select a specific TimePeriod from dropdown."
			+ "User should be able to validate Discount Removed button."
			+ "If remove button is visible than user should be able to click on Remove button."
			+ "By clicking remove button amount also should be changed accordingly."
			+ "User should be able to validate Coin Count and the coin count should be 10% of Product price."
			+ "User should be able to click on BUY button." + "User should be able to fill userDetails form."
			+ "User should able to click on continue button." + "User should be able to see payment option screen."
			+ "User should be able to click UPI payment option." + "Validate UPI payment screen."
			+ "User should be able to enter UPI Id." + "User should be able to see the same Product amount."
			+ "User should be able to click on PayNow button." + "User should be able to see the RateUs PopUp."
			+ "User should be able to close RateUs PopUp window." + "User should be able to verify OrderSuccess page."
			+ "User should be able to see the same Product amount on OrderSuccess page.";

	public final static String verifyPDPWithDiscount = "User should be able to create package Videos package through API."
			+ "User should be able to get Package title and Primary Validity time."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click store btn" + "User should be able to verify store page."
			+ "User should be able to search package title through search icon."
			+ "User should be able to see Created package and able to click it."
			+ "User should be able to see Primary Validity time period."
			+ "User should be able to select a specific TimePeriod from dropdown."
			+ "User should be able to validate Discount Removed button."
			+ "If remove button is visible than user should be able to click on Remove button."
			+ "By clicking remove button amount also should be changed accordingly."
			+ "User should be able to click on CoinCount check box and after that amount should be substracted from product price and the substracted price should be 10% of Coin count amount."
			+ "User should be able to open PriceDetails page by click on OffLink."
			+ "User should be able to verify the coin user amount and total amount and UseCoin check box."
			+ "User should be able to close priceDetails page." + "User should be able to click on BUY button."
			+ "User should be able to fill userDetails form." + "User should able to click on continue button."
			+ "User should be able to see payment option screen." + "User should be able to click UPI payment option."
			+ "Validate UPI payment screen." + "User should be able to enter UPI Id."
			+ "User should be able to see the same Product amount." + "User should be able to click on PayNow button."
			+ "User should be able to see the RateUs PopUp." + "User should be able to close RateUs PopUp window."
			+ "User should be able to verify OrderSuccess page."
			+ "User should be able to see the same Product amount on OrderSuccess page.";

	public final static String verifyPDPWithZeroAmount = "User should be able to create package EBook package through API."
			+ "User should be able to get Package title and Primary Validity time."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click store btn" + "User should be able to verify store page."
			+ "User should be able to search package title through search icon."
			+ "User should be able to see Created package and able to click it."
			+ "User should be able to see Primary Validity time period."
			+ "User should be able to select a specific TimePeriod from dropdown."
			+ "User should be able to validate Discount Removed button."
			+ "If remove button is visible than user should be able to click on Remove button."
			+ "By clicking remove button amount also should be changed accordingly."
			+ "User should be able to apply Coupon(AUTOMATION)." + "Product price should be changed to Zero."
			+ "User should be able to validate Discount amount and saved amount should be same."
			+ "User should not be able to enable UseCoin CheckBox." + "User should be able to click on BUY button."
			+ "User should be able to fill userDetails form." + "User should able to click on continue button."
			+ "User should be able to see the RateUs PopUp." + "User should be able to close RateUs PopUp window."
			+ "User should be able to verify OrderSuccess page."
			+ "User should be able to see the same Product amount on OrderSuccess page.";

	public final static String verifyPDPWithCoupon = "User should be able to create package Videos package through API."
			+ "User should be able create Coupon through API."
			+ "User should be able to get Package title and Primary Validity time."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click store btn" + "User should be able to verify store page."
			+ "User should be able to search package title through search icon."
			+ "User should be able to see Created package and able to click it."
			+ "User should be able to see Primary Validity time period."
			+ "User should be able to select each validity time period."
			+ "User should be able to apply generated Coupon on each validity time Period."
			+ "User should be able to see 10% deducted product amount after Coupon Applied."
			+ "User should be able to validate Discount Removed button."
			+ "If remove button is visible than user should be able to click on Remove button."
			+ "By clicking remove button amount also should be changed accordingly."
			+ "User should be able to click on BUY button." + "User should be able to fill userDetails form."
			+ "User should able to click on continue button." + "User should be able to see payment option screen."
			+ "User should be able to click UPI payment option." + "Validate UPI payment screen."
			+ "User should be able to enter UPI Id." + "User should be able to see the same Product amount."
			+ "User should be able to click on PayNow button." + "User should be able to see the RateUs PopUp."
			+ "User should be able to close RateUs PopUp window." + "User should be able to verify OrderSuccess page."
			+ "User should be able to see the same Product amount on OrderSuccess page.";

	public final static String verifyPDPWithDefaultCoupon = "User should be able to create package Videos package through API."
			+ "User should be able create Coupon through API."
			+ "User should be able to make the Created coupon default."
			+ "User should be able to get Package title and Primary Validity time."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to click store btn" + "User should be able to verify store page."
			+ "User should be able to search package title through search icon."
			+ "User should be able to see Created package and able to click it."
			+ "User should be able to see Primary Validity time period."
			+ "User should be able to select each validity time period."
			+ "user should be able to see the created coupon code,Coupon applied text and Remove button on each validity time period."
			+ "User should be able to click on BUY button." + "User should be able to fill userDetails form."
			+ "User should able to click on continue button." + "User should be able to see payment option screen."
			+ "User should be able to click UPI payment option." + "Validate UPI payment screen."
			+ "User should be able to enter UPI Id." + "User should be able to see the same Product amount."
			+ "User should be able to click on PayNow button." + "User should be able to see the RateUs PopUp."
			+ "User should be able to close RateUs PopUp window." + "User should be able to verify OrderSuccess page."
			+ "User should be able to see the same Product amount on OrderSuccess page.";

	public final static String verifyUserProfileScreenNew = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to open side drawer." + "User should be able to change the Night Mode."
			+ "User should be able to click on user profile section on Side drawer."
			+ "User should be able to validate user profile screen."
			+ "User should be able to see the correct Like,Post,Comment count."
			+ "User should be able to close User profile screen by click on back button."
			+ "User should land on Home Page." + "User should be able to click on Community tab."
			+ "User should land on Community page." + "User should be able to create a post."
			+ "User should be able to like the Created post." + "User should be able to Bookmark the Created post."
			+ "User should be able to comment button on created post."
			+ "User should be able to post comment on comment page."
			+ "User should be able to navigate to user profile screen by click On user name on Comment page."
			+ "User should be able to see correct Like,Post,Comment count."
			+ "User should be able to open FollowFollowing screen by click on Followers button."
			+ "User should be able to remove user from Follower screen."
			+ "User should be able to Follow a user and unfollow a user in Following screen.";

	public final static String verifyOtherUserProfileScreen = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to open side drawer." + "User should be able to change the Night Mode."
			+ "User should be able to click on user profile section on Side drawer."
			+ "User should be able to validate user profile screen."
			+ "User should be able to open FollowFollowing screen by click on Following tab."
			+ "User should be able to see Faculty user name in Following screen."
			+ "User should be able to open Faculty user profile by click on Faculty user name."
			+ "User should be able to validate Faculty user profile screen and Faculty tag should be visible."
			+ "User should be able to open FollowFollowing screen by click on Followers Tab."
			+ "User should be able to Follow and unFollow user in FollowFollowing screen."
			+ "User should be able to close FollowFollowing screen by click on back button."
			+ "User should land on Faculty user profile screen."
			+ "User should be able to open MyCourse screen by click on MyCourse tab and close By click on close button."
			+ "User should land on user Faculty user Profile screen."
			+ "User should be able to open Activity screen by click on AllActivity button."
			+ "User should be able to validate Activity screen."
			+ "User should be able to close Activity screen by click on close button."
			+ "User should land on Faculty user profile screen."
			+ "User should be able to open BookMark screen by click on Bookmark button."
			+ "User should be able to validate Bookmark screen."
			+ "User should be able to close Bookmark screen by click on back button."
			+ "User should land on Faculty user Profile screen."
			+ "User should be able to open 3 Dot bottomsheet by click on Dot icon."
			+ "User should be able to see CopyProfileLink and Report cell on Botton Sheet."
			+ "User should be able to copy the link by on CopyProfileLink tab."
			+ "User should be able to report profile by click on Report tab."
			+ "User should land FollowFollowing screen after reporting the profile."
			+ "User should be able to open Other user profile screen by click on Other user name."
			+ "User should be able to validate Other user profile screen."
			+ "User should be able to open FollowFollowing screen by click on Followers Tab."
			+ "User should be able to Follow and unFollow user in FollowFollowing screen."
			+ "User should be able to close FollowFollowing screen by click on back button."
			+ "User should land on Other user profile screen."
			+ "User should be able to open Activity screen by click on AllActivity button."
			+ "User should be able to validate Activity screen."
			+ "User should be able to close Activity screen by click on close button."
			+ "User should land on Other user profile screen."
			+ "User should be able to Follow/UnFollow user by click onFollowFollowing button."
			+ "User should be able to open 3 Dot bottomsheet by click on Dot icon."
			+ "User should be able to see CopyProfileLink and Report cell on Botton Sheet."
			+ "User should be able to copy the link by on CopyProfileLink tab."
			+ "User should be able to report profile by click on Report tab."
			+ "User should land FollowFollowing screen after reporting the profile.";

	public final static String verifyEditPersonalDetailsTab = "User should be able to push an image to emulator/Physical device."
			+ "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to open side drawer."
			+ "User should be able to click on user profile section on Side drawer."
			+ "User should be able to see correct Like,Post,Comment count."
			+ "User should be able to close user profile screen by click on back button."
			+ "User should land on Home Page." + "User should be able to click on Community tab."
			+ "User should land on Community page." + "User should be able to create a post."
			+ "User should be able to like the Created post." + "User should be able to Bookmark the Created post."
			+ "User should be able to comment button on created post."
			+ "User should be able to post comment on comment page."
			+ "User should be able to navigate to user profile screen by click On user name on Comment page."
			+ "User should be able to open Bookmark screen by click on Bookmark button."
			+ "User should be able to see empty state in each tab section on Bookmark screen."
			+ "User should be able to add materials in Bookmark screen through emptystate button present in each tab section."
			+ "User should be able to close Bookmark screen by click on Back button."
			+ "User should be able to open 3Dot bottom sheet by click on Dot icon."
			+ "User should be able to see CopyProfileLink,EditPersonalInformation,CoinBalance,MyOrder,Setting,Logout tab."
			+ "User should be able to see CopyProfileLink and Report cell on Botton Sheet."
			+ "User should be able to copy the link by on CopyProfileLink tab."
			+ "User should be able to open EditPersonalInformation screen by click on Edit Personal Information tab."
			+ "User should be able to close EditPersonalInformation screen by click on back button."
			+ "User should be able to open CoinBalance page by click on CoinBalance Tab and close by click on back button."
			+ "User should be able to open and validate MyOrder screenby click on MyOrder tab and close by click on back button."
			+ "User should be able to open and validate setting page by click on Setting tab and close by click on back button."
			+ "User should land on User Profile screen."
			+ "User should be able to open EditPersonalInformation screen by click on ProfileEdit button."
			+ "User should be able to validate EditPersonalInformation screen."
			+ "User should be able to set profilePicture,name,MobileNumber,Password,DOB,Gender,Category,About."
			+ "User should able to save the changes by click on Save button."
			+ "User should land on User Profile screen and user able to see the Changes."
			+ "User should be able to  Logout by click on Dot icon and Logout tab."
			+ "User should be able to loging again with the new Password." + "User should land on Home Page.";

	public final static String verifyFacultyUserProfileScreen = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should land on Home Page." + "User should be able to click on Community tab."
			+ "User should land on Community page." + "User should be able to create a MCQ post."
			+ "User should be able to comment button on created post."
			+ "User should be able to post comment on comment page."
			+ "User should be able to navigate to user profile screen by click On comment_UserName,Comment_userPic,Reply_userName,Reply_userPic."
			+ "User should be able to validate User profile screen."
			+ "user should be able to open and validate MyCourse page by click on MyCourse button and close by click on back button."
			+ "User should be able to open Bookmark screen by click on Bookmark button."
			+ "User should be able to validate Bookmark screen."
			+ "User should be able to close Bookmark screen by click on Back button."
			+ "User should be able to open Activity screen by click on AllActivity button."
			+ "User should be able to validate Activity screen."
			+ "User should be able to close Activity screen by click on Back button."
			+ "User should be able to open 3Dot bottom sheet by click on Dot icon."
			+ "User should be able to see CopyProfileLink,EditPersonalInformation,CoinBalance,MyOrder,Setting,Logout tab."
			+ "User should be able to see CopyProfileLink and Report cell on Botton Sheet."
			+ "User should be able to copy the link by on CopyProfileLink tab."
			+ "User should be able to open EditPersonalInformation screen by click on Edit Personal Information tab."
			+ "User should be able to close EditPersonalInformation screen by click on back button."
			+ "User should be able to open CoinBalance page by click on CoinBalance Tab and close by click on back button."
			+ "User should be able to open and validate MyOrder screenby click on MyOrder tab and close by click on back button."
			+ "User should be able to open and validate setting page by click on Setting tab and close by click on back button."
			+ "User should be able to  Logout by click on Logout tab.";

	public final static String verifyMCQPostInAllActivityTab = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should land on Home Page." + "User should be able to click on Community tab."
			+ "User should land on Community page." + "User should be able to create a MCQ post."
			+ "User should be able to open side drawer."
			+ "User should be able to click on user profile section on Side drawer."
			+ "User should be able to see correct Like,Post,Comment count."
			+ "User should be able to open Bookmark screen by click on bookmark button."
			+ "User should be able to see Empty state inside Post section."
			+ "User should be able to close Bookmark screen by click on back button."
			+ "User should be able to open Activity screen by click on AllActivity button."
			+ "User should be able to see MCQ post inside AllPost section."
			+ "User should be able to add and remove like and based on that post should displayed inside Like section. "
			+ "User should be able to add ,edit and delete comment and based on that post should displayed inside Comment section."
			+ "User should be able to attempt the mock and the mock should be visible inside MCQ section."
			+ "User should be able to delete the MCQ post."
			+ "User should be able to close Activity screen by click on back button."
			+ "User should be able to close user profile screen by click on Back button."
			+ "User should be able to click on community button." + "User should be able to open side drawer."
			+ "User should be able to click on user profile section on Side drawer."
			+ "User should be able to see correct Like,Post,Comment count.";

	public final static String verifyMCQPostInBookMarkPostsTab = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should land on Home Page." + "User should be able to click on Community tab."
			+ "User should land on Community page." + "User should be able to create a MCQ post."
			+ "User should be able to open side drawer."
			+ "User should be able to click on user profile section on Side drawer."
			+ "User should be able to see correct Like,Post,Comment count."
			+ "User should be able to open Activity screen by click on AllActivity button."
			+ "User should be able to see MCQ post inside AllPost section." + "user should be able to share Mcq post."
			+ "User should be able to open Post comment page." + "User should be able to add and remove like ."
			+ "User should be able to add ,edit and delete comment."
			+ "User should be able to attempt the mock and the mock should be visible inside MCQ section."
			+ "user should be able to Bookmark the post." + "User should be able to delete the MCQ post."
			+ "User should be able to close the Comment page." + "User should be able to validate deleted post."
			+ "User should be able to delete the Shared post."
			+ "User should be able to close Activity screen by click on back button."
			+ "User should be able to close user profile screen by click on Back button."
			+ "User should be able to click on community button." + "User should be able to create a MCQ post."
			+ "User should be able to open side drawer."
			+ "User should be able to click on user profile section on Side drawer."
			+ "User should be able to open Activity screen by click on AllActivity button."
			+ "User should be able to add Post in bookmark." + "User should be able to share the post."
			+ "User should be able to close Activity screen by click on AllActivity button."
			+ "User should be able to open Bookmark screen by click on Bookmark button."
			+ "User should be able to see MCQ post in Post section." + "User should be able to add and remove like ."
			+ "User should be able to add ,edit and delete comment."
			+ "User should be able to attempt the mock and the mock should be visible inside MCQ section."
			+ "user should be able to remove Bookmark the post." + "User should be able to share the post."
			+ "User should be able to delete the MCQ post.";

	public final static String verifyUserScreenFromHomePage = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to able to open comment screen by click on Post comment button."
			+ "User should be able to post Comment and reply comment."
			+ "User should navigate to user profile screen by click on Comment_userName and Reply_userName."
			+ "User should be able to validate user profile screen."
			+ "User should be able to see Correct Like,Post,Comment count."
			+ "User should be able to open Activity screen by click on AllActivity button."
			+ "User should be able to validate Activity screen."
			+ "User should be able to Close Activity screen by click on back buttom."
			+ "User should be able to open Bookmark screen by click on Bookmark button."
			+ "User should be able to validate Bookmark screen."
			+ "User should be able to Close Bookmark screen by click on back buttom."
			+ "user should be able to validate FollowFollowing screen."
			+ "User should be able to open Purchased screen by click on MyPurchase button."
			+ "User should be able to validate Purchased screen.";

	public final static String verifyUserProfileDeepLink = "User should be able to click on login/register button."
			+ "Enter user name and password than click on login button" + "User should able to login."
			+ "User should be able to able to open comment screen by click on Post comment button."
			+ "User should be able to post DeepLink."
			+ "User should navigate to user profile screen by click on deeplink posted in Comment page."
			+ "User should be able to validate user profile screen."
			+ "User should be able to close User profile screen by click on Back button."
			+ "User should be able to click on Home tab." + "User should be able to open side drawer."
			+ "User should be able to click on user profile section on Side drawer."
			+ "User should be able to open 3Dot bottomSheet by click on Dot icon."
			+ "User should be abloe to Copy profile link by click on CopyProfileLink tab."
			+ "User should be able to close User profile screen by click on back button."
			+ "User should be able to click on Home tab." + "User should be able to click on Community page."
			+ "User should be able to Create MCQ post."
			+ "User should be able to post profile link on post comment page."
			+ "User should be able to open User profile screen by click on Profile link."
			+ "User should be able to validate User profile screen."
			+ "User should be able to open Activity screen by click on AllActivity button."
			+ "User should be able to validate Activity screen Ui."
			+ "User should be able to close Activity screen by click on back button."
			+ "User should be able to open Bookmark screen by click on Bookmark button."
			+ "User should be able to validate Bookmark screen Ui."
			+ "User should be able to close Bookmark screen by click on back button."
			+ "user should be able open EditPersonalInformation screen by click on Profile edit button."
			+ "User should be able to validate EditPersonalInformation screen."
			+ "User should be able to close EditPersonalInformation screen by click on Back button."
			+ "User should be able to open FollowFollowing screen by click on Following tab."
			+ "User should be able to open Faculty profile screen by click on Faculty user name."
			+ "User should be able to open 3Dot bottomSheet by click on Dot icon."
			+ "User should be abloe to Copy profile link by click on CopyProfileLink tab."
			+ "User should be able to close User profile screen by click on back button."
			+ "User should be able to close FollowFollowing screen by click on back button."
			+ "User should be able to open Activity screen by click on AllActivity button."
			+ "user should be able to enter deepLink on postComment page."
			+ "User should be able to open user profile screen by click on DeepLink."
			+ "User should be able to open Activity screen by click on AllActivity button."
			+ "User should be able to validate Activity screen Ui."
			+ "User should be able to close Activity screen by click on back button."
			+ "User should be able to open Bookmark screen by click on Bookmark button."
			+ "User should be able to validate Bookmark screen Ui."
			+ "User should be able to close Bookmark screen by click on back button."
			+ "user should be able to open and validate MyCouresPage by click on MyCourse button."
			+ "User should be able to close MyCourse page by click on Back button."
			+ "User should be able to validate FollowFollowing button.";

	public final static String verfiyLoginGuestUser = "user should be able to open application and choose Environment."
			+ "User should be able to select Category." + "user should land not SelectExam screen."
			+ "User should be able to select Exam type and should land on Select Language screen."
			+ "user should be able to select language and should land on application home screen."
			+ "User should be able to click Email/Phone button" + "User should land on Signup screen."
			+ "user should be able to click on login link." + "user should land on Login screen."
			+ "User should be able to enter Mobile/Email and password on textField."
			+ "user should be able to click on Login button."
			+ "User should be able to handle mobileNumber textfield popup."
			+ "user should land on home page and should be able to validate Home page.";

	public final static String verfiyLoginNewUser = "user should be able to register an Email through Api."
			+ "user should be able to open application and choose Environment."
			+ "User should be able to select Category." + "user should land not SelectExam screen."
			+ "User should be able to select Exam type and should land on Select Language screen."
			+ "user should be able to select language and should land on application home screen."
			+ "User should be able to click Email/Phone button" + "User should land on Signup screen."
			+ "user should be able to click on login link." + "user should land on Login screen."
			+ "User should be able to enter Mobile/Email and password on textField."
			+ "user should be able to click on Login button."
			+ "User should be able to handle mobileNumber textfield popup."
			+ "user should land on home page and should be able to validate Home page.";

	public final static String verfiyLoginGuestUserWithImageCompare = "user should be able to open application and choose Environment."
			+ "User should be able to compare Select Category screen." + "User should be able to select Category."
			+ "User should be able to compare Select Exam screen." + "user should land on SelectExam screen."
			+ "User should be able to select Exam type and should land on Select Language screen."
			+ "User should be able to compare Select language screen."
			+ "user should be able to select language and should land on application home screen."
			+ "User should be able to compare All four type of image present in Home screen."
			+ "User should be able to click Email/Phone button" + "User should be able to compare SignUp screen."
			+ "User should land on Signup screen." + "user should be able to click on login link."
			+ "user should land on Login screen." + "User should be able to compare Login screen."
			+ "User should be able to enter Mobile/Email and password on textField."
			+ "user should be able to click on Login button."
			+ "User should be able to compare mobileNumber textfield popup screen."
			+ "User should be able to handle mobileNumber textfield popup."
			+ "user should land on home page and should be able to validate Home page.";

	public final static String verifyLogout = "user should be able to open application and choose Environment."
			+ "User should be able to select Category." + "user should land not SelectExam screen."
			+ "User should be able to select Exam type and should land on Select Language screen."
			+ "user should be able to select language and should land on application home screen."
			+ "User should be able to click Email/Phone button" + "User should land on Signup screen."
			+ "user should be able to click on login link." + "user should land on Login screen."
			+ "User should be able to enter Mobile/Email and password on textField."
			+ "user should be able to click on Login button."
			+ "User should be able to handle mobileNumber textfield popup."
			+ "user should land on home page and should be able to validate Home page."
			+ "User should be able to click side Drawer."
			+ "user should be able to open user profile screen by click on user section."
			+ "User should be able to open 3Dot bottonSheet by click on Dot icon."
			+ "User should be able to open logOut Confirmation popup by click on logout tab."
			+ "user should be able to logout by click on logout button."
			+ "User should land on application HomeScreen.";

	public final static String verifySignUp = "user should be able to register an Email through Api."
			+ "user should be able to open application and choose Environment."
			+ "User should be able to select Category." + "user should land not SelectExam screen."
			+ "User should be able to select Exam type and should land on Select Language screen."
			+ "user should be able to select language and should land on application home screen."
			+ "User should be able to click Email/Phone button" + "User should land on Signup screen."
			+ "user should be able to enter Mobile number in Mobile number textField."
			+ "User should be able to open OTP popup screen by click on generate OTP button."
			+ "User should be able to enter Otp." + "user should land on SignUp Details Form screen."
			+ "user should be able to fill all the datails."
			+ "user should be able to open Home screen by click on signup button."
			+ "user should land on home page and should be able to validate Home page.";

		public final static String verfiyGoogleLogin = "user should be able to open application and choose Environment."
			+ "User should be able to compare Select Category screen." + "User should be able to select Category."
			+ "User should be able to compare Select Exam screen." + "user should land on SelectExam screen."
			+ "User should be able to select Exam type and should land on Select Language screen."
			+ "click on google login button" + "User should be able to login with google";
}
